set(_CATKIN_CURRENT_PACKAGE "my_new_package")
set(my_new_package_VERSION "0.0.0")
set(my_new_package_MAINTAINER "elijah <elijah@todo.todo>")
set(my_new_package_PACKAGE_FORMAT "2")
set(my_new_package_BUILD_DEPENDS "roscpp" "std_msgs")
set(my_new_package_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(my_new_package_BUILDTOOL_DEPENDS "catkin")
set(my_new_package_BUILDTOOL_EXPORT_DEPENDS )
set(my_new_package_EXEC_DEPENDS "roscpp" "std_msgs")
set(my_new_package_RUN_DEPENDS "roscpp" "std_msgs")
set(my_new_package_TEST_DEPENDS )
set(my_new_package_DOC_DEPENDS )
set(my_new_package_URL_WEBSITE "")
set(my_new_package_URL_BUGTRACKER "")
set(my_new_package_URL_REPOSITORY "")
set(my_new_package_DEPRECATED "")